### PR TITLE
update(readme): added extra options to how to run section.

### PR DESCRIPTION
**Pull request by ashwinjadhav818**
Added a section to use yasb with the installer given in the releases.

### CODE REVIEW

**Comment by amnweb** [comment]
Maybe add some **note** about the installer that is still unstable and crashing can be expected when the config is changed?
Also, I'm tired and can't thinking :( but please let me know why we need to import function_map inside base?

**Comment by ashwinjadhav818** [comment]
Added a note about the installer being unstable.

The function_map is needed inside base so that in-build widgets like volume, wifi, battery can also use the functions on their callbacks not only custom widgets.

**Comment by amnweb** [comment]
So if you call `quick_settings` from callbacks `left_click`, it should be triggered from all widgets. Did you try this?
Something like this ?

```
callbacks:
  on_left: "quick_settings"
```

**Comment by ashwinjadhav818** [comment]
yeahh but it should be `exec quick_settings`

**Pull request merged**
