### PR TITLE
added config_schema.json for the config.yaml file.

### PR DESCRIPTION
**Pull request by Alan-Manning**
#Config.yaml schema

config.yaml schema for ease of setting up when first using it.
This is pretty bare bones for now but provides usefull information as to what to configure and also what the defaults are if you make an error in the config.

Please let me know if there is anything more you would like to see from this and i can try add it.
I couldnt see much about how you would like pull requests formatted so i hope this is ok.

Thank you
 - Alan manning.

### CODE REVIEW

**Comment by amnweb** [comment]
Actually, this can be very useful. I'm currently working on animations that will require changing the config again, so maybe it's better to wait to finish with animations and then we can continue to talk about this PR?

https://github.com/user-attachments/assets/e18306db-3781-4ec4-9729-e7d967987af9

**Comment by Alan-Manning** [comment]
Yeah no worries, should be easy to extend it when you have that.
 - Alan Manning

**Comment by amnweb** [comment]
@Alan-Manning I have totally forgotten about this PR :( 
If you are still interested in implementing the schema for the config file, I think it is better to close this PR and start with a new one, this one looks confusing xD or we can talk and discuss on Discord about this because I think some widgets must be excluded from the schema, like the custom widget.

**Comment by Alan-Manning** [comment]
> @Alan-Manning I have totally forgotten about this PR :( If you are still interested in implementing the schema for the config file, I think it is better to close this PR and start with a new one, this one looks confusing xD or we can talk and discuss on Discord about this because I think some widgets must be excluded from the schema, like the custom widget.

Yeah no worries. I have some code that generates a schema but it's now outdated and also not the best because it doesn't cover all things and I think didn't pull from the validators which would be best probably. I may revisit this at some point and I will probably discuss on discord first.

**Pull request closed without merging**
